[project]
name = "liszt-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "py-cord>=2.6.1",
    "pycord>=0.1.1",
    "python-dotenv>=1.0.1",
]
